apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: myspringbootapp
  namespace: default
spec:
  selector:
    app: myspringbootapp
  type: LoadBalancer
  ports:
  - name: myspringbootapp
    protocol: TCP
    port: 80
    targetPort: 9099
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30036 