pipeline {
    agent any

    parameters{

        choice(name: "action", choices: 'create\ndestroy\ndestroyekscluster', description: 'Create/Update or destroy the eks cluster')
        string(name:'cluster', defaultValue: 'demo-cluster', description: 'Eks cluster name')
        string(name:'regions', defaultValue: 'us-east-1', description: 'Eks cluster region')
    }



stages{

        stage ("Git Checkout"){
            steps {

                git branch: 'main', url: 'https://github.com/CaptainDemir/demo-app2.git'
            
            }

        }


                stage ("eks connect"){
            steps {

                sh""""

                 aws eks --region ${params.region} --name ${param.cluster}

                """;

                
            
            }

        }


/*         stage ("eks deployment"){
            
            steps {
                when { expression { param.action== "create"}

                }

               sctrips {
                   
                   def apply = false
                   try {
                       input message: 'please confirm the apply to initiate the deployments', ok "Ready to apply the config"
                       apply = true

                   }

                   catch(err){
                     apply = false
                     CurrentBuild.result= "UNSTABLE"
                     
                    }
                    if(apply){
                        
                        sh """
                              kubectl apply -f .
                        """;
                    }


               }
            
            }

        } */

}

}